from typing import Any, Iterator, NoReturn

class SimulatedEntityHandle:
    def __new__(cls, *args: Any, **kwargs: Any) -> NoReturn: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...

class MergeInfo:
    merged: tuple[SimulatedEntityHandle, SimulatedEntityHandle]
    into: SimulatedEntityHandle

    def __new__(cls, *args: Any, **kwargs: Any) -> NoReturn: ...

class NativeSimulationCore:
    def __init__(
        self,
        gravitational_constant: float,
        softening_factor: float,
        enable_merging: bool,
        merge_distance_squared: float,
    ) -> None: ...
    def create(
        self, px: float, py: float, vx: float, vy: float, mass: float
    ) -> SimulatedEntityHandle: ...
    def is_handle_valid(self, handle: SimulatedEntityHandle) -> bool: ...
    def get(
        self, handle: SimulatedEntityHandle
    ) -> tuple[float, float, float, float, float]: ...
    def set_position(
        self, handle: SimulatedEntityHandle, x: float, y: float
    ) -> None: ...
    def set_velocity(
        self, handle: SimulatedEntityHandle, x: float, y: float
    ) -> None: ...
    def set_mass(self, handle: SimulatedEntityHandle, mass: float) -> None: ...
    def delete(self, handle: SimulatedEntityHandle) -> None: ...
    def entities_in_rect_iter(
        self, tlx: float, tly: float, brx: float, bry: float
    ) -> Iterator[SimulatedEntityHandle]: ...
    def center_of_mass(self) -> tuple[float, float]: ...
    def update(self, dt: float) -> list[MergeInfo]: ...
